openwisp_radius/saml/urls.py
from django.urls import path

from .. import settings as app_settings


def get_saml_urls(saml_views=None):
    if not app_settings.SAML_LOGIN_ENABLED:
        return []

    if not saml_views:
        # Need to import views inside the function because SAML
        # is an optional setup and dependencies might not be
        # installed on all systems.
        from . import views

        saml_views = views

    return [
        path(
            'login/',
            saml_views.LoginView.as_view(),
            name='saml2_login',
        ),
        path(
            'acs/',
            saml_views.AssertionConsumerServiceView.as_view(),
            name='saml2_acs',
        ),
        path(
            'logout/',
            saml_views.LogoutInitView.as_view(),
            name='saml2_logout',
        ),
        path('ls/', saml_views.LogoutView.as_view(), name='saml2_ls'),
        path(
            'ls/post/',
            saml_views.LogoutView.as_view(),
            name='saml2_ls_post',
        ),
        path(
            'metadata/',
            saml_views.MetadataView.as_view(),
            name='saml2_metadata',
        ),
    ]

openwisp_radius/urls.py
from django.urls import include, path

from .api.urls import get_api_urls
from .private_storage.urls import get_private_store_urls
from .saml.urls import get_saml_urls
from .social.urls import get_social_urls


def get_urls(api_views=None, social_views=None, saml_views=None):
    """
    Returns a list of urlpatterns
    Arguements:
        api_views(optional): views for Radius API
        social_view(optional): views for social login (if enabled)
        saml_views(optional): views for saml login (if enabled)
    """
    return [
        path('api/v1/', include(get_api_urls(api_views))),
        path('api/v1/', include(get_private_store_urls())),
        path('radius/social-login/', include(get_social_urls(social_views))),
        path('radius/saml2/', include(get_saml_urls(saml_views))),
    ]


# Cannot used 'app_name' here because when the radius
# urls are not registered, yet we want to get url reverse
# using urlconf we still want radius to be our namespace.
namespace = 'radius'
urlpatterns = [path('', include((get_urls(), namespace), namespace=namespace))]

openwisp_radius/templates/djangosaml2/auth_error.html
{% extends "account/base.html" %}
{% load i18n %}

{% block content %}
    <h1>{% trans "Authorization error" %}</h1>
    <p>{% blocktrans %}You are already logged in and you are trying to access the login page again.{% endblocktrans %}</p>
    <p>{% blocktrans %}You may have been redirected here when trying to access some content
       that required extra privileges that you do not have.{% endblocktrans %}</p>
    <p>{% trans "Please logout and login as a different user" %}.</p>
    <p><a class="button" href="{% url 'radius:saml2_logout' %}">{% trans "logout" %}</a></p>
{% endblock %}

openwisp_radius/templates/djangosaml2/login_error.html
{% extends "account/base.html" %}
{% load i18n %}

{% block content %}
    <h1>{% trans "Authentication Error" %}</h1>
    <h2>{% trans "Access Denied" %}</h2>
{% endblock %}

openwisp_radius/templates/djangosaml2/logout_error.html
{% extends "account/base.html" %}
{% load i18n %}

{% block content %}
    <h1>{% trans "Logout Error" %}</h1>
    <p>{% blocktrans %}Your Identity Provider ask this system to do a global logout but your federated session is lost.{% endblocktrans %}</p>

    <p>{% blocktrans %}Even if your local session in this system has been closed, you have probably open sessions in other systems.{% endblocktrans %}</p>

    <p>{% blocktrans %}In order to prevent illicit use of your personal information, please close your browser window and/or remove your cookies from your browser.{% endblocktrans %}</p>

    <p>{% blocktrans %}Sorry for this inconvenience.{% endblocktrans %} </p>
{% endblock %}

openwisp_radius/templates/djangosaml2/wayf.html
{% extends "account/base.html" %}
{% load i18n %}

{% block content %}
    <h1>{% trans "Where are you from?" %}</h1>
    <p>{% trans "Please select your" %} <strong>{% trans "Identity Provider" %}</strong> {% trans "from the following list" %}</p>
    <ul>
        {% for url, name in available_idps %}
        <li><a
                href="{% url 'radius:saml2_login' %}?idp={{ url }}{% if came_from %}&next={{ came_from }}{% endif %}">{{ name|default_if_none:url }}</a>
        </li>
        {% endfor %}
    </ul>
{% endblock %}